### ISSUE TITLE
Govip does not keep track of the etcd cluster leader

### ISSUE THREAD

**Issue by lars301** [retinadata/govip#2]
1. cat go.mod
module govip

go 1.17

replace github.com/coreos/bbolt v1.3.4 => go.etcd.io/bbolt v1.3.4

replace google.golang.org/grpc => google.golang.org/grpc v1.26.0

require (
        github.com/coreos/etcd v3.3.27+incompatible
        github.com/j-keck/arping v1.0.2
        github.com/sirupsen/logrus v1.8.1
        github.com/vishvananda/netlink v1.1.0
        go.etcd.io/etcd v3.3.27+incompatible
)

require (
        github.com/coreos/bbolt v1.3.4 // indirect
        github.com/coreos/go-semver v0.3.0 // indirect
        github.com/coreos/go-systemd v0.0.0-20191104093116-d3cd4ed1dbcf // indirect
        github.com/coreos/pkg v0.0.0-20180928190104-399ea9e2e55f // indirect
        github.com/dgrijalva/jwt-go v3.2.0+incompatible // indirect
        github.com/dustin/go-humanize v1.0.0 // indirect
        github.com/gogo/protobuf v1.3.2 // indirect
        github.com/golang/protobuf v1.5.2 // indirect
        github.com/google/uuid v1.3.0 // indirect
        github.com/grpc-ecosystem/go-grpc-middleware v1.3.0 // indirect
        github.com/grpc-ecosystem/go-grpc-prometheus v1.2.0 // indirect
        github.com/grpc-ecosystem/grpc-gateway v1.16.0 // indirect
        github.com/jonboulle/clockwork v0.2.2 // indirect
        github.com/pkg/errors v0.9.1 // indirect
        github.com/prometheus/client_golang v1.12.1 // indirect
        github.com/soheilhy/cmux v0.1.5 // indirect
        github.com/tmc/grpc-websocket-proxy v0.0.0-20220101234140-673ab2c3ae75 // indirect
        github.com/vishvananda/netns v0.0.0-20191106174202-0a2b9b5464df // indirect
        github.com/xiang90/probing v0.0.0-20190116061207-43a291ad63a2 // indirect
        go.uber.org/atomic v1.7.0 // indirect
        go.uber.org/multierr v1.6.0 // indirect
        go.uber.org/zap v1.21.0 // indirect
        golang.org/x/crypto v0.0.0-20220214200702-86341886e292 // indirect
        golang.org/x/net v0.0.0-20211123203042-d83791d6bcd9 // indirect
        golang.org/x/sys v0.0.0-20220114195835-da31bd327af9 // indirect
        golang.org/x/text v0.3.6 // indirect
        google.golang.org/genproto v0.0.0-20200825200019-8632dd797987 // indirect
        google.golang.org/grpc v1.33.1 // indirect
        google.golang.org/protobuf v1.26.0 // indirect
        gopkg.in/yaml.v2 v2.4.0 // indirect
        sigs.k8s.io/yaml v1.3.0 // indirect
)
2.  etcdctl -w table --endpoints https://t2mq-etest-01.corp.ru:2379,https://t2mq-etest-02.corp.ru:2379,https://t2mq-etest-03.corp.ru:2379 endpoint status
+------------------------------------------+------------------+---------+---------+-----------+-----------+------------+
|                 ENDPOINT                 |        ID        | VERSION | DB SIZE | IS LEADER | RAFT TERM | RAFT INDEX |
+------------------------------------------+------------------+---------+---------+-----------+-----------+------------+
| https://t2mq-etest-01.corp.ru:2379 | 801bf8247d37306a |  3.3.11 |   41 kB |     false |       799 |    1046828 |
| https://t2mq-etest-02.corp.ru:2379 | fcca74f6cfed122c |  3.3.11 |   41 kB |      true |       799 |    1046828 |
| https://t2mq-etest-03.corp.ru:2379 | ed2e63afd0e103cb |  3.3.11 |   41 kB |     false |       799 |    1046828 |
+------------------------------------------+------------------+---------+---------+-----------+-----------+------------+

etcdctl --endpoints [https://t2mq-etest-01.corp.ru:2379,https://t2mq-etest-02.corp.ru:2379,https://t2mq-etest-03.corp.ru:2379](https://t2mq-etest-01.corp.ru:2379%2Chttps//t2mq-etest-02.corp.ru:2379,https://t2mq-etest-03.corp.ru:2379) get '' --prefix
/govip//306a7f0bcbace22d
t2mq-etest-01.corp.ru
/govip//3cb7f1b7da9e576
t2mq-etest-03.corp.ru
/govip//3cb7f1b7da9e578
t2mq-etest-02.corp.ru

3. Logging
Feb 21 14:21:22 t2mq-etest-01 systemd[1]: Started govip virtual-ip service.
Feb 21 14:21:27 t2mq-etest-01 govip[43844]: time="2022-02-21T14:21:27+03:00" level=info msg="IP address set, sending gratuitous ARPs"

Feb 21 14:21:22 t2mq-etest-02 systemd[1]: Started govip virtual-ip service.

Feb 21 14:21:22 t2mq-etest-03 systemd[1]: Started govip virtual-ip service.

**Comment by agaoglu** [comment]
I think what you're trying to say is, your etcd leader is etest-02 but govip chooses etest-01 to announce the VIP. And yes, it can do that.

Why do you want your vip to follow your etcd leader exactly?

**Comment by lars301** [comment]
Hi. Thanks for the answer.
In description "..Instances will try to become the election leader and claim the VIP address only when they succeed."
Doesn't that mean the vip follows the etcd leader?

On etest-01
sudo systemctl stop etcd.service
etcdctl -w table --endpoints https://t2mq-etest-01.corp.ru:2379,https://t2mq-etest-02.corp.ru:2379,https://t2mq-etest-03.corp.ru:2379 endpoint status
Failed to get the status of endpoint https://t2mq-etest-01.corp.ru:2379 (context deadline exceeded)
+------------------------------------------+------------------+---------+---------+-----------+-----------+------------+
|                 ENDPOINT                 |        ID        | VERSION | DB SIZE | IS LEADER | RAFT TERM | RAFT INDEX |
+------------------------------------------+------------------+---------+---------+-----------+-----------+------------+
| https://t2mq-etest-02.corp.ru:2379 | fcca74f6cfed122c |  3.3.11 |   41 kB |      true |       799 |    1061119 |
| https://t2mq-etest-03.corp.ru:2379 | ed2e63afd0e103cb |  3.3.11 |   41 kB |     false |       799 |    1061119 |
+------------------------------------------+------------------+---------+---------+-----------+-----------+------------+

VIP stays on the node etest-01 and does not move to another node.

sudo systemctl stop govip.service

VIP moved to node etest-03.

This is normal, predefined behavior of the program?
Thanks.

**Comment by agaoglu** [comment]
> Doesn't that mean the vip follows the etcd leader?

No, this election is different from what etcd uses to promote its own leader and followers. It's for govip instances only. It's possible to run govip and etcd on different hosts, for example. govip is using [etcd concurrency API](https://etcd.io/docs/v3.3/dev-guide/api_concurrency_reference_v3/#service-election-etcdserverapiv3electionv3electionpbv3electionproto) to be specific.

> sudo systemctl stop etcd.service

And as you've shown, it's possible for etcd cluster to change its leader for whatever reason, without affecting the govip leader. 

> sudo systemctl stop govip.service

Or vice-versa. If you stop one govip instance on a node, another govip instance will become leader, but it won't affect the etcd leader.

**Comment by lars301** [comment]
Thank you for your responses.
